In [1]:
import pybithumb
import pandas as pd
import numpy as np

In [10]:
def test01(date='2019', ticker='BTC'):
    df = pybithumb.get_ohlcv(ticker)
    df = df[date]
    
    # 전일 ma3, 전일 ma8
    df['ma3'] = df['close'].rolling(window=3).mean().shift(1)
    df['ma8'] = df['close'].rolling(window=8).mean().shift(1)
    
    # range
    df['range'] = (df['high'].shift(1) - df['low'].shift(1)) * k
    
    df.dropna(inplace=True)
    df = df.astype(int)
    return df

In [11]:
test01()

,open,high,low,close,volume,ma3,ma8
2019-01-09 00:00:00,4522000,4573000,4404000,4440000,17055,4446333,4336375
2019-01-10 00:00:00,4441000,4485000,4220000,4243000,5620,4488666,4369000
2019-01-11 00:00:00,4242000,4259000,4047000,4098000,5988,4403000,4361625
2019-01-12 00:00:00,4098000,4157000,4050000,4092000,3036,4260333,4335125
2019-01-13 00:00:00,4094000,4120000,4055000,4058000,1861,4144333,4313875
2019-01-14 00:00:00,4057000,4073000,3942000,3978000,4261,4082666,4283750
2019-01-15 00:00:00,3978000,4149000,3973000,4094000,3901,4042666,4241875
2019-01-16 00:00:00,4094000,4100000,4000000,4060000,4522,4043333,4191125
2019-01-17 00:00:00,4060000,4075000,4005000,4031000,3212,4044000,4132875
2019-01-18 00:00:00,4030000,4087000,4025000,4040000,3074,4061666,4081750
2019-01-19 00:00:00,4038000,4180000,4022000,4121000,3162,4043666,4056375
2019-01-20 00:00:00,4120000,4144000,3924000,3975000,2659,4064000,4059250
2019-01-21 00:00:00,3970000,4000000,3945000,3974000,2680,4045333,4044625
2019-01-22 00:00:00,3973000,4022000,3900000,4004000,3687,4023333,4034125
2019-01-23 00:00:00,4004000,4049000,3977000,3994000,3457,3984333,4037375
2019-01-24 00:00:00,3996000,4004000,3951000,3972000,2939,3990666,4024875
2019-01-25 00:00:00,3972000,4000000,3907000,3940000,2869,3990000,4013875
2019-01-26 00:00:00,3942000,4040000,3933000,3963000,2264,3968666,4002500
2019-01-27 00:00:00,3971000,3983000,3900000,3945000,2040,3958333,3992875
2019-01-28 00:00:00,3946000,3968000,3784000,3825000,3664,3949333,3970875
2019-01-29 00:00:00,3825000,3848000,3736000,3796000,3556,3911000,3952125
2019-01-30 00:00:00,3800000,3849000,3769000,3811000,3494,3855333,3929875
2019-01-31 00:00:00,3811000,3849000,3762000,3762000,3821,3810666,3905750
2019-02-01 00:00:00,3766000,3815000,3740000,3808000,2687,3789666,3876750
2019-02-02 00:00:00,3807000,3832000,3789000,3820000,1755,3793666,3856250
2019-02-03 00:00:00,3821000,3867000,3799000,3818000,1489,3796666,3841250
2019-02-04 00:00:00,3818000,3847000,3795000,3812000,1771,3815333,3823125
2019-02-05 00:00:00,3812000,3847000,3810000,3826000,1565,3816666,3806500
2019-02-06 00:00:00,3826000,3850000,3770000,3774000,2494,3818666,3806625
2019-02-07 00:00:00,3774000,3805000,3759000,3791000,2613,3804000,3803875
...,...,...,...,...,...,...,...
2019-06-25 00:00:00,12801000,13500000,12720000,13329000,8119,12562666,11662250
2019-06-26 00:00:00,13329000,15610000,13323000,15258000,18017,12855333,11935875
2019-06-27 00:00:00,15220000,16858000,13808000,14602000,32378,13796000,12480375
2019-06-28 00:00:00,14599000,15020000,12959000,14566000,25946,14396333,12947000
2019-06-29 00:00:00,14566000,15411000,14235000,14651000,12486,14808666,13375375
2019-06-30 00:00:00,14651000,14898000,13778000,13917000,7742,14606333,13761750
2019-07-01 00:00:00,13908000,14273000,12504000,12532000,14163,14378000,13945000
2019-07-02 00:00:00,12542000,13163000,11746000,12851000,23706,13700000,13957000
2019-07-03 00:00:00,12851000,14000000,12630000,13748000,17512,13100000,13963250
2019-07-04 00:00:00,13742000,14516000,13431000,14251000,11932,13043666,14015625
2019-07-05 00:00:00,14251000,14299000,13068000,13697000,11215,13616666,13889750
2019-07-06 00:00:00,13709000,13921000,13150000,13680000,6748,13898666,13776625
2019-07-07 00:00:00,13678000,13980000,13385000,13569000,5070,13876000,13665875
2019-07-08 00:00:00,13569000,14280000,13405000,14175000,7428,13648666,13530625
2019-07-09 00:00:00,14168000,15181000,14067000,14617000,13083,13808000,13562875
2019-07-10 00:00:00,14617000,15542000,14515000,14903000,12124,14120333,13823500
2019-07-11 00:00:00,14900000,14933000,13544000,14157000,20056,14565000,14080000
2019-07-12 00:00:00,14163000,14251000,13234000,13959000,13472,14559000,14131125
2019-07-13 00:00:00,13959000,14298000,13610000,13737000,5947,14339666,14094625
2019-07-14 00:00:00,13729000,13899000,12819000,12886000,9607,13951000,14099625
2019-07-15 00:00:00,12886000,13120000,11879000,12695000,15438,13527333,14000375
2019-07-16 00:00:00,12695000,13451000,12500000,12563000,11514,13106000,13891125
2019-07-17 00:00:00,12550000,12737000,10870000,11626000,22932,12714666,13689625
2019-07-18 00:00:00,11626000,12300000,11093000,12175000,15114,12294666,13315750
2019-07-19 00:00:00,12175000,12800000,12035000,12347000,14365,12121333,12974750
2019-07-20 00:00:00,12348000,12745000,12308000,12580000,5370,12049333,12748500
2019-07-21 00:00:00,12580000,13109000,12295000,12350000,7764,12367333,12576125
2019-07-22 00:00:00,12340000,12684000,12155000,12222000,4471,12425666,12402750
2019-07-23 00:00:00,12218000,12420000,11835000,11938000,5848,12384000,12319750
2019-07-24 12:00:00,11938000,12180000,11401000,11473000,3456,12170000,12225125